version: '3'
services:
  api:
    build: ./nest-image
    user: root
    working_dir: /api
    deploy:
      replicas: 1
    volumes:
      - ./:/api
    ports:
      - '3333:3333'
    command: 'yarn start api'
    environment:
      - NODE_ENV=development
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data/pgdata
